name: ngoc_huong
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+2
environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  localstorage: ^4.0.1+2
  flutter_datetime_picker_bdaya: ^3.0.1
  dio: ^5.3.2
  url_launcher: ^6.1.12
  star_rating: ^0.11.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.6.3
  elegant_notification: ^1.10.0
  timezone: ^0.9.2
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.9
  app_settings: ^5.0.0
  flutter_animate: ^4.2.0
  file_picker: ^6.1.1
  open_file: ^3.3.2
  pin_code_fields: ^8.0.1
  flutter_easyloading: ^3.0.5
  loading_indicator: ^3.1.1
  flutter_localization: ^0.1.13
  badges: ^3.1.2
  dots_indicator: ^3.0.0
  scroll_to_hide: ^2.0.1
  upgrader: ^8.4.0
  video_player: ^2.8.1
  mobile_scanner: ^4.0.1
  flutter_barcode_scanner: ^2.0.0
  photo_view: ^0.14.0
  flutter_widget_from_html: ^0.14.11
  flutter_rating_stars: ^1.0.3+4
  qr_code_scanner: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/login/banner.jpg
    - assets/images/icon/profile-red.png
    - assets/images/voucher.png
    - assets/images/voucher1.png
    - assets/images/coupon.png
    - assets/images/thanh-toan.png
    - assets/images/calendar-solid-red.png
    - assets/images/calendar-white.png
    - assets/images/cart-black.png
    - assets/images/cart-white.png
    - assets/images/nam-white.png
    - assets/images/nam-black.png
    - assets/images/nu-white.png
    - assets/images/nu-black.png
    - assets/images/call-solid-red.png
    - assets/images/location-solid-black.png
    - assets/images/location-green.png
    - assets/images/time-solid-black.png
    - assets/images/TimeCircleBlack.png
    - assets/images/calendar-black.png
    - assets/images/call-black.png
    - assets/images/delete-black.png
    - assets/images/delete-red.png
    - assets/images/cod.png
    - assets/images/chuyen-khoan.png
    - assets/images/messenger-red.png
    - assets/images/zalo1.png
    - assets/images/x.png
    - assets/images/award.png
    - assets/images/Home/Services/thanh-vien.png
    - assets/images/giftbox.png
    - assets/images/location-to.png
    - assets/images/calendar-solid-black.png
    - assets/images/Home/banner-sale.png
    - assets/images/Notifications/noti1.png
    - assets/images/Notifications/bell1.png
    - assets/images/Notifications/bell2.png
    - assets/images/account/thong-tin.png
    - assets/images/account/giao-dich.png
    - assets/images/account/dat-lich.png
    - assets/images/account/dieu-khoan.png
    - assets/images/account/file-white.png
    - assets/images/account/gioi-thieu.png
    - assets/images/account/dia-chi.png
    - assets/images/account/ve-chung-toi.png
    - assets/images/account/dang-xuat.png
    - assets/images/account/img.webp
    - assets/images/account/voucher.png
    - assets/images/dieu-tri.png
    - assets/images/may.png
    - assets/images/editing.png
    - assets/images/star-solid.png
    - assets/images/star-outline.png
    - assets/images/tre-hoa.png
    - assets/images/waxing.png
    - assets/images/banner-flash.png
    - assets/images/icon/cart.png
    - assets/images/icon/icon1.png
    - assets/images/icon/home.png
    - assets/images/icon/dich-vu.png
    - assets/images/icon/my-pham.png
    - assets/images/icon/tu-van.png
    - assets/images/icon/Xu.png
    - assets/images/icon/Xu1.png
    - assets/images/icon/QR-fanpage.png
    - assets/images/icon/checkin.png
    - assets/images/icon/icon-vi-tri.jpg
    - assets/images/icon/gift.png
    - assets/intro/intro.MP4
    - assets/intro/intro1.MP4
    - assets/intro/start.mp4
    - assets/images/rank/BAC.png
    - assets/images/rank/VANG.png
    - assets/images/rank/BACHKIM.png
    - assets/images/rank/KIMCUONG.png
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Thin.ttf
          weight: 200
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
          weight: 800
    - family: Quicksand
      fonts:
        - asset: assets/fonts/font/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/font/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/font/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/font/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/font/Quicksand-Bold.ttf
          weight: 700
