// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFBZplNIfoFf2KH-lc06JuvyXtZ1VBYas',
    appId: '1:83126216779:web:70f28678c25a6eac4245ce',
    messagingSenderId: '83126216779',
    projectId: 'fir-ngoc-huong',
    authDomain: 'fir-ngoc-huong.firebaseapp.com',
    storageBucket: 'fir-ngoc-huong.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv5HTUKVom46q7a94O5IyvnC3q1yPUXCU',
    appId: '1:83126216779:android:ed4e82fc11c99e3f4245ce',
    messagingSenderId: '83126216779',
    projectId: 'fir-ngoc-huong',
    storageBucket: 'fir-ngoc-huong.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUPVxehojdwINSk16SAFtPEXu1lAmM1x8',
    appId: '1:83126216779:ios:f8a4bab9269a2bc14245ce',
    messagingSenderId: '83126216779',
    projectId: 'fir-ngoc-huong',
    storageBucket: 'fir-ngoc-huong.appspot.com',
    iosClientId: '83126216779-p16vo0uuqhkmsl1elbf3e8a2d6qhs1lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngocHuong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUPVxehojdwINSk16SAFtPEXu1lAmM1x8',
    appId: '1:83126216779:ios:f8a4bab9269a2bc14245ce',
    messagingSenderId: '83126216779',
    projectId: 'fir-ngoc-huong',
    storageBucket: 'fir-ngoc-huong.appspot.com',
    iosClientId: '83126216779-p16vo0uuqhkmsl1elbf3e8a2d6qhs1lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngocHuong',
  );
}
